idf_component_register(
    SRCS "main.c" "vibe_board.c" "vibe_audio.c" "vibe_power_policy.c" "../generated/vibe_stick_cn_16.c" "../generated/vibe_stick_ui_assets.c" "../generated/vibe_roxy_assets.c"
    INCLUDE_DIRS "../include" "../generated"
    REQUIRES esp_wifi esp_http_client esp_event esp_netif nvs_flash json driver esp_timer esp_lcd esp_codec_dev esp_pm
)
